import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // A leading underscore is our convention for "intentionally unused —
      // kept for a function signature / interface the caller relies on"
      // (e.g. a no-op that still needs to match its original params).
      // eslint-config-next's default doesn't recognize this pattern.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/build-report-fonts.mjs — each file is one ~150KB
    // base64 string literal. Nothing to lint, and parsing them on every run
    // costs real time.
    "src/assets/fonts/generated/**",
  ]),
]);

export default eslintConfig;
