import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

interface PDFTemplateProps {
  projectName: string;
  logoUrl?: string | null;
  period: string;
  content: ParsedReportContent;
  primaryColor?: string;
}

interface ParsedReportContent {
  sections: Array<{ heading: string; body: string }>;
  rawMarkdown: string;
}

const NAVY = "#1B2A4A";
const BODY = "#374151";
const LIGHT_GRAY = "#F3F4F6";
const MID_GRAY = "#9CA3AF";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    paddingTop: 72,
    paddingBottom: 72,
    paddingHorizontal: 72,
    fontSize: 10,
    color: BODY,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: LIGHT_GRAY,
  },
  projectName: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: NAVY,
  },
  headerRight: {
    fontSize: 9,
    color: MID_GRAY,
    textAlign: "right",
  },
  h1: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: NAVY,
    marginTop: 16,
    marginBottom: 6,
  },
  h2: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: NAVY,
    marginTop: 12,
    marginBottom: 4,
  },
  paragraph: {
    fontSize: 10,
    color: BODY,
    lineHeight: 1.5,
    marginBottom: 8,
  },
  footer: {
    position: "absolute",
    bottom: 36,
    left: 72,
    right: 72,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: MID_GRAY,
    borderTopWidth: 1,
    borderTopColor: LIGHT_GRAY,
    paddingTop: 6,
  },
});

export function parseMarkdown(markdown: string): ParsedReportContent {
  const sections: Array<{ heading: string; body: string }> = [];
  const lines = markdown.split("\n");
  let currentHeading = "";
  let currentBody: string[] = [];

  for (const line of lines) {
    if (line.startsWith("### ") || line.startsWith("## ")) {
      if (currentHeading) {
        sections.push({ heading: currentHeading, body: currentBody.join("\n").trim() });
      }
      currentHeading = line.replace(/^#+\s+/, "");
      currentBody = [];
    } else {
      currentBody.push(line);
    }
  }
  if (currentHeading) {
    sections.push({ heading: currentHeading, body: currentBody.join("\n").trim() });
  }

  return { sections, rawMarkdown: markdown };
}

export function VaultBriefPDF({
  projectName,
  period,
  content,
  primaryColor = NAVY,
}: PDFTemplateProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={[styles.projectName, { color: primaryColor }]}>
            {projectName}
          </Text>
          <Text style={styles.headerRight}>
            Monthly Investor Report{"\n"}
            {period}
          </Text>
        </View>

        {/* Content */}
        {content.sections.map((section, i) => (
          <View key={i}>
            <Text style={section.heading.startsWith("###") ? styles.h2 : styles.h1}>
              {section.heading}
            </Text>
            {section.body.split("\n").map((line, j) => {
              if (!line.trim()) return null;
              // Bullet points
              if (line.startsWith("- ") || line.startsWith("• ")) {
                return (
                  <Text key={j} style={[styles.paragraph, { marginLeft: 12 }]}>
                    {"• "}
                    {line.replace(/^[-•]\s+/, "")}
                  </Text>
                );
              }
              return (
                <Text key={j} style={styles.paragraph}>
                  {line}
                </Text>
              );
            })}
          </View>
        ))}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text>Generated by VaultBrief</Text>
          <Text
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}
